# Generated by Django 5.2.10 on 2026-07-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='design/')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='journal/')),
                ('entry_date', models.DateField()),
                ('tag', models.CharField(choices=[('interior-design', 'Interior design'), ('gardening', 'Gardening'), ('small-spaces', 'Small spaces'), ('curation', 'Curation')], default='curation', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
