# Generated by Django 5.2.10 on 2026-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_instagram_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from public grids without deleting.'),
        ),
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entries', models.ManyToManyField(blank=True, related_name='collections', to='journal.journalentry')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
