# Generated by Django 5.2.10 on 2026-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_seed_florals_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small grid preview; auto-generated from photo when missing.', upload_to='journal/thumbs/'),
        ),
    ]
