# Generated by Django 5.2.10 on 2026-07-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Connor Brown', max_length=120)),
                ('handle', models.CharField(blank=True, default='@connorbrown', max_length=80)),
                ('blurb', models.TextField(blank=True, default='', help_text='Public bio shown on the About Me page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About profile',
                'verbose_name_plural': 'About profile',
            },
        ),
    ]
